### ISSUE TITLE
vs 2019 not available

### ISSUE THREAD

**Issue by andrewpros** [aberus/StackOverflowQuickLaunch#5]
Hi.

Despite the description on marketplace that the extension supports 2019 and a version of 1.0, the vsix wont show vs 2019 to install the extension, not sure there was a mistake or its something on my side?

**Comment by mcquiggd** [comment]
@andrewpros, @aberus 

 I've created a [pull request](https://github.com/aberus/StackOverflowQuickLaunch/pull/6) to address this.

If you need to use it in the meantime, you can do the following:

1. Download the vsix file.
2. Install 7-Zip, if you do not already have it.
3. Open the vsix file in 7-Zip (do not extract it, just open it).
4. Right click on extension.vsixmanifest and select "Edit".
5. Paste the following over the lines between `<Installation ...> </Installation>`

```
    <InstallationTarget Version="[12.0, 17.0]" Id="Microsoft.VisualStudio.Community" />
    <InstallationTarget Version="[12.0, 17.0]" Id="Microsoft.VisualStudio.Pro" />
    <InstallationTarget Version="[12.0, 17.0]" Id="Microsoft.VisualStudio.Enterprise" />
```

So, the end result looks like this:

```
<Installation InstalledByMsi="false">
    <InstallationTarget Version="[12.0, 17.0]" Id="Microsoft.VisualStudio.Community" />
    <InstallationTarget Version="[12.0, 17.0]" Id="Microsoft.VisualStudio.Pro" />
    <InstallationTarget Version="[12.0, 17.0]" Id="Microsoft.VisualStudio.Enterprise" />
</Installation>
```

6. Save this file (Ctrl-s).
7. 7-Zip will prompt you to update the archive with the changed file, click yes.
8. Exit 7-Zip and run the vsix as normal.

I am using it with VS 2019 Enterprise and VS 2019 Enterprise Preview - works fine.

**Comment by andrewpros** [comment]
@mcquiggd thx, works

**Comment by mcquiggd** [comment]
@andrewpros Glad to help.. I am seeing this a lot in extensions with regard to Visual Studio 2019; it's an easy mistake to make.

**Comment by andrewpros** [comment]
This is odd, the code supports vs 2019, but u cant install it.

**Comment by mcquiggd** [comment]
The manifest for the VSIX specifies requirements that prevent the installation from completing.

Correcting those entries as I mention above will mean the VSIX will install, and the code functions as intended...

**Comment by andrewpros** [comment]
Yeah i know and i planed to modify the manifest myself but wasn't sure the code supports 2019 already, then u posted instructions so i was almost sure the code supports it, its just odd to me to make such tiny mistake.

**Comment by aberus** [comment]
Current extension supports VS 2019, but Microsoft changed search experience in VS 2019. New search does not support extensibility 😞. Searching errors form error list still works.
I intended to add a disclaimer on the marketplace, but it somehow fell through the cracks.

Thank you for reporting your issue.

![Untitled](https://user-images.githubusercontent.com/2404410/60806660-e2d66580-a183-11e9-9d6b-611f14105974.png)
